### ISSUE TITLE
We are facing issue with Grid css 

### ISSUE THREAD

**Issue by jaysinghsoni** [appreciated/material#30] opened 2017-09-14 13:09 UTC
we are using the material theme in our recent project and there is some issue with Grid display with material however with Valo theme Grid css display work decently below are the points which need fixes i also have attached the grid display with material and valo theme for your reference

1. With Multi Selection Mode check box width goes out with the grid rows
2. Default alternate coloring of valo theme for grid not working with material 
3. rows height needs as with valo 

you can also help me with how can i skip that material theme will not apply on grid component this will fix me for current situation
![valo](https://user-images.githubusercontent.com/30683885/30431367-fe95cbb0-997b-11e7-8d64-b8334c2e0aea.png)
![material](https://user-images.githubusercontent.com/30683885/30431368-fe9fddb2-997b-11e7-850f-0701bf820fff.png)

**Comment by appreciated** [comment] 2017-09-14 14:54
From the wiki:
> The Material Theme relies on the Valo theme engine, this means you are able to use all style names that are presented in the Valo Theme. But you shouldn't use all the scss variables shown in the Valo API to manipulate the Material Theme.
> To show what is left of Valo's variables, and what else can be done to archive different looks take a look into the Material SCSS-Variables.

The Problem is that Valo actually isn't quite "compatible" with the Material design, thats why many of its features needed to be overwritten / are being ignored / needed to be added within the Material Theme. 

Valo might allow you to change the border radius, the flattness, colors and much more, very easily, but when I started to get single UI Elements close to how they are supposed to be in Material Design I pretty fast found a lot of things that simply required to overwrite a lot. 

This exactly happened in the Grid, which probably leeds to the style issues shown above. 

I recommand to remove (or outcomment if you prefer switching to valo later on) any valo grid stylings you applied in your custom theme to get your style issues removed, then you can start using material variables to style the grid.

**Comment by jaysinghsoni** [comment] 2017-09-15 06:38
Thanks for your reply 
i have not used valo theme the only theme i am using is material and also i have not added any special style in the grid code i have just test the code with valo theme while take the snap to demo the look and feel of the grid with valo also i will not use the valo since i am happy with the material theme so if you feel free you can help me out to get the style look and feel with material with the current issue i am not very good with css and the grid style is so complex so if you can point any suggestions it will be good Thanks

**Comment by appreciated** [comment] 2017-09-15 09:35
If you could supply the minimal code to reproduce the issue this would be great. The images alone aren't really helping me.

**Comment by appreciated** [comment] 2017-09-16 12:13
I tracked the issue down I hope its fixed now. Please check if the fix worked for you aswell!

**Closed as completed** 2017-09-16 13:03 UTC
